tap "blacktop/tap"
tap "homebrew/cask"
tap "homebrew/core"
tap "homeport/tap"
tap "mistertea/et"
tap "noahgorstein/tap"
tap "noborus/tap"
tap "sandreas/tap"
tap "wader/tap"
brew "ack"
brew "argp-standalone"
brew "aria2"
brew "asciidoctor"
brew "autoconf"
brew "automake"
brew "bettercap"
brew "binwalk"
brew "libevent"
brew "bitcoin"
brew "node"
brew "bitwarden-cli"
brew "boost"
brew "boost-bcp"
brew "brew-gem"
brew "bsdiff"
brew "caddy", restart_service: :changed
brew "cloc"
brew "colordiff"
brew "cpdf"
brew "cython"
brew "dhcpdump"
brew "dhex"
brew "diffoscope"
brew "diskus"
brew "djvulibre"
brew "dosbox-staging"
brew "entr"
brew "exif"
brew "exiftool"
brew "fd"
brew "fdupes"
brew "gmp"
brew "fheroes2"
brew "libtool"
brew "fontforge", link: false
brew "gtk+3"
brew "freeciv"
brew "fzf"
brew "gh"
brew "go"
brew "gocloc"
brew "gojq"
brew "gource"
brew "graphviz"
brew "haskell-stack"
brew "id3v2"
brew "libimobiledevice"
brew "ideviceinstaller"
brew "jq"
brew "ijq"
brew "imagemagick"
brew "iperf3"
brew "jqp"
brew "ldns"
brew "leveldb"
brew "lux"
brew "mas"
brew "miller"
brew "mosh"
brew "mp3check"
brew "mp3unicode"
brew "mpv"
brew "mtr"
brew "mupdf"
brew "ncdu"
brew "ncspot"
brew "nethack"
brew "nmap"
brew "openvpn"
brew "ov"
brew "pandoc"
brew "pgxnclient"
brew "pipx"
brew "poetry"
brew "postgresql@15", restart_service: :changed, link: true
brew "postgresql@17"
brew "privoxy"
brew "pstree"
brew "pv"
brew "qemu"
brew "qpdf"
brew "qrencode"
brew "radare2"
brew "rclone"
brew "rename"
brew "rlwrap"
brew "rtorrent"
brew "sevenzip"
brew "sl"
brew "speedtest-cli"
brew "tcping"
brew "telnet"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "tmux"
brew "tor", restart_service: :changed
brew "torsocks"
brew "tree"
brew "uv"
brew "vbindiff"
brew "watch"
brew "watchexec"
brew "wget"
brew "winetricks"
brew "wireshark"
brew "xmp"
brew "yarn"
brew "blacktop/tap/ipsw"
brew "homeport/tap/termshot"
brew "mistertea/et/et"
brew "sandreas/tap/m4b-tool"
brew "wader/tap/fq"
cask "anki"
cask "anytype"
cask "appcleaner"
cask "audiobook-builder"
cask "bindiff"
cask "bitcoin-core"
cask "bitwarden"
cask "bluewallet"
cask "coconutbattery"
cask "deltachat"
cask "discord"
cask "dosbox"
cask "dyalog"
cask "electrum"
cask "etrecheckpro"
cask "figma-agent"
cask "firefox"
cask "fontforge-app"
cask "horos"
cask "iina"
cask "inkscape"
cask "karabiner-elements"
cask "kextviewr"
cask "knockknock"
cask "logseq"
cask "losslesscut"
cask "lulu"
cask "macdown"
cask "macfuse"
cask "meld"
cask "musescore"
cask "obsidian"
cask "onyx"
cask "signal"
cask "sparrow"
cask "specter"
cask "steam"
cask "stremio"
cask "taskexplorer"
cask "telegram"
cask "tencent-meeting"
cask "the-unarchiver"
cask "tor-browser"
cask "tunnelblick"
cask "wechat"
cask "whatsapp"
cask "xquartz"
cask "zalo"
cask "zoom"
mas "BeagleIM", id: 1445349494
mas "Bee DICOM Viewer", id: 1590273176
mas "Blixt Wallet", id: 0
mas "Chordio", id: 1580214821
mas "EasyRes", id: 688211836
mas "Exporter", id: 1099120373
mas "GarageBand", id: 682658836
mas "hide.me", id: 953040671
mas "HolaVPN2", id: 1553473179
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "LookUp", id: 872564448
mas "NetWorker Pro", id: 1163602886
mas "Numbers", id: 409203825
mas "Outline", id: 1356178125
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "Remote Desktop", id: 409907375
mas "Shadowrocket", id: 932747118
mas "Speedtest", id: 1153157709
mas "Tampermonkey Classic", id: 1482490089
mas "TestFlight", id: 899247664
mas "uBlock Origin Lite", id: 6745342698
mas "Userscripts", id: 1463298887
mas "WiFi Signal", id: 525912054
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
go "github.com/in3rsha/bitcoin-utxo-dump"
