tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homeport/tap"
tap "noahgorstein/tap"
tap "noborus/tap"
tap "wader/tap"
brew "ack"
brew "argp-standalone"
brew "aria2"
brew "asciidoctor"
brew "autoconf"
brew "automake"
brew "bettercap"
brew "binwalk"
brew "libevent"
brew "bitcoin"
brew "node"
brew "bitwarden-cli"
brew "boost"
brew "boost-bcp"
brew "brew-gem"
brew "bsdiff"
brew "caddy", restart_service: :changed
brew "cloc"
brew "colordiff"
brew "cython"
brew "dhcpdump"
brew "dhex"
brew "diffoscope"
brew "diskus"
brew "djvulibre"
brew "entr"
brew "exif"
brew "exiftool"
brew "fd"
brew "fdupes"
brew "gmp"
brew "fheroes2"
brew "gtk+3"
brew "freeciv"
brew "fzf"
brew "gh"
brew "go"
brew "gocloc"
brew "gojq"
brew "gource"
brew "libtool"
brew "graphviz"
brew "haskell-stack"
brew "jq"
brew "ijq"
brew "imagemagick"
brew "iperf3"
brew "ldns"
brew "leveldb"
brew "lux"
brew "mas"
brew "miller"
brew "mosh"
brew "mpv"
brew "mtr"
brew "ncdu"
brew "ncspot"
brew "nethack"
brew "nmap"
brew "pandoc"
brew "pgxnclient"
brew "pipx"
brew "poetry"
brew "postgresql@15", restart_service: :changed, link: true
brew "postgresql@17"
brew "privoxy"
brew "pstree"
brew "pv"
brew "qemu"
brew "qrencode"
brew "radare2"
brew "rclone"
brew "rename"
brew "rlwrap"
brew "rtorrent"
brew "sevenzip"
brew "sl"
brew "speedtest-cli"
brew "tcping"
brew "telnet"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "tmux"
brew "tor", restart_service: :changed
brew "torsocks"
brew "tree"
brew "vbindiff"
brew "watch"
brew "watchexec"
brew "wget"
brew "winetricks"
brew "wireshark"
brew "xmp"
brew "yarn"
brew "zenity"
brew "homeport/tap/termshot"
brew "noahgorstein/tap/jqp"
brew "noborus/tap/ov"
brew "wader/tap/fq"
cask "anki"
cask "anytype"
cask "appcleaner"
cask "arc"
cask "bindiff"
cask "bitcoin-core"
cask "bitwarden"
cask "bluewallet"
cask "coconutbattery"
cask "discord"
cask "djview"
cask "dyalog"
cask "electrum"
cask "etrecheckpro"
cask "firefox"
cask "gstreamer-runtime"
cask "iina"
cask "inkscape"
cask "iterm2"
cask "karabiner-elements"
cask "kextviewr"
cask "knockknock"
cask "lark"
cask "logseq"
cask "lulu"
cask "macfuse"
cask "obsidian"
cask "onyx"
cask "orion"
cask "signal"
cask "sloth"
cask "sparrow"
cask "specter"
cask "telegram"
cask "the-unarchiver"
cask "tor-browser"
cask "tunnelblick"
cask "utm"
cask "vlc"
cask "vnc-viewer"
cask "wechat"
cask "whatsapp"
cask "whisky"
cask "wine-stable"
cask "xquartz"
cask "zalo"
cask "zoom"
mas "BeagleIM", id: 1445349494
mas "Chordio", id: 1580214821
mas "EasyRes", id: 688211836
mas "Exporter", id: 1099120373
mas "GarageBand", id: 682658836
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "NetWorker Pro", id: 1163602886
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Remote Desktop", id: 409907375
mas "TestFlight", id: 899247664
mas "Userscripts-Mac-App", id: 1463298887
mas "WiFi Signal", id: 525912054
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
